"""Dataset statistics and figures for the report (BUILD_SPEC M3.5).

Writes ``docs/dataset_stats.md`` (windows per activity and split, subjects per split),
``docs/figures/class_distribution.png`` and ``docs/figures/sample_windows.png``. Output has
no timestamps, so regenerating from the same data gives the same files. Entry point:
``python scripts/data_report.py``.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

import numpy as np
from matplotlib.figure import Figure

from har.data.constants import ACTIVITY_NAMES, CHANNELS, N_CLASSES, N_FEATURES, WINDOW_LEN
from har.data.splits import load_val_subjects, read_subjects, train_val_masks
from har.utils.paths import SPLIT_FILE, UCI_DIR

SPLITS = ("train", "val", "test")
SAMPLE_RATE_HZ = 50

# Chart styling: categorical slots 1-3 of the validated default palette, in fixed order
# (blue, orange, aqua), plus recessive chrome. Counts are also in the markdown table.
SERIES = ("#2a78d6", "#eb6834", "#1baf7a")
SURFACE = "#ffffff"
INK, INK_SECONDARY, INK_MUTED = "#0b0b0b", "#52514e", "#898781"
GRID, BASELINE = "#e1e0d9", "#c3c2b7"


def activity_label(name: str) -> str:
    """``WALKING_UPSTAIRS -> Walking upstairs``."""
    return name.replace("_", " ").capitalize()


def read_labels(split: Literal["train", "test"], uci_dir: Path = UCI_DIR) -> np.ndarray:
    """Activity index 0..5 of every window in ``y_<split>.txt``: int64 ``(N,)``."""
    path = Path(uci_dir) / split / f"y_{split}.txt"
    if not path.is_file():
        raise FileNotFoundError(f"{path} not found; run python -m har.data.download")
    y = np.loadtxt(path, dtype=np.int64, ndmin=1)
    if y.min() < 1 or y.max() > N_CLASSES:
        raise ValueError(f"{path}: labels must be in 1..{N_CLASSES}, got {y.min()}..{y.max()}")
    return y - 1


def summarise_splits(uci_dir: Path = UCI_DIR, split_file: Path = SPLIT_FILE) -> dict[str, dict]:
    """Labels and subjects of the train / val / test windows under the committed split.

    Returns ``{split: {"labels": int64 (N,), "subjects": int64 (N,)}}`` for ``SPLITS``.
    """
    y_all, s_all = read_labels("train", uci_dir), read_subjects("train", uci_dir)
    if len(y_all) != len(s_all):
        raise ValueError(f"train: {len(y_all)} labels but {len(s_all)} subject ids")
    train_mask, val_mask = train_val_masks(s_all, load_val_subjects(split_file))
    y_test, s_test = read_labels("test", uci_dir), read_subjects("test", uci_dir)
    if len(y_test) != len(s_test):
        raise ValueError(f"test: {len(y_test)} labels but {len(s_test)} subject ids")
    return {
        "train": {"labels": y_all[train_mask], "subjects": s_all[train_mask]},
        "val": {"labels": y_all[val_mask], "subjects": s_all[val_mask]},
        "test": {"labels": y_test, "subjects": s_test},
    }


def class_counts(labels: np.ndarray, n_classes: int = N_CLASSES) -> np.ndarray:
    """Windows per class ``(n_classes,)``; absent classes count 0."""
    return np.bincount(np.asarray(labels, dtype=np.int64), minlength=n_classes)


def stats_markdown(summary: dict[str, dict], figures: dict[str, str] | None = None) -> str:
    """The ``dataset_stats.md`` text. ``figures`` maps a caption to a path relative to the file."""
    counts = {s: class_counts(summary[s]["labels"]) for s in SPLITS}
    totals = {s: int(counts[s].sum()) for s in SPLITS}
    grand = sum(totals.values())

    lines = [
        "# UCI HAR dataset statistics",
        "",
        "Generated by `python scripts/data_report.py` from `data/raw/UCI HAR Dataset` and "
        "`configs/split.json`. Do not edit by hand.",
        "",
        f"Each window is {WINDOW_LEN} samples ({WINDOW_LEN / SAMPLE_RATE_HZ:.2f} s at "
        f"{SAMPLE_RATE_HZ} Hz, 50% overlap) of {len(CHANNELS)} inertial channels; the dataset "
        f"also provides {N_FEATURES} engineered features per window. "
        "Train and val are the official training subjects split by subject; test is the official test split.",
        "",
        "## Windows per activity and split",
        "",
        "Percentages are of the split's windows.",
        "",
        "| Activity | Train | Val | Test | Total |",
        "|---|---:|---:|---:|---:|",
    ]
    for c, name in enumerate(ACTIVITY_NAMES):
        cells = [f"{int(counts[s][c]):,} ({100 * counts[s][c] / totals[s]:.1f}%)" for s in SPLITS]
        lines.append(f"| {name} | " + " | ".join(cells) + f" | {sum(int(counts[s][c]) for s in SPLITS):,} |")
    lines.append("| **Total** | " + " | ".join(f"**{totals[s]:,}**" for s in SPLITS) + f" | **{grand:,}** |")

    lines += [
        "",
        "## Subjects per split",
        "",
        "| Split | Subjects | Count | Windows | Windows per subject (min to max) |",
        "|---|---|---:|---:|---|",
    ]
    for s in SPLITS:
        ids, per_subject = np.unique(summary[s]["subjects"], return_counts=True)
        lines.append(
            f"| {s.capitalize()} | {', '.join(str(int(i)) for i in ids)} | {len(ids)} | "
            f"{totals[s]:,} | {int(per_subject.min())} to {int(per_subject.max())} |"
        )

    if figures:
        lines += ["", "## Figures", ""]
        for caption, rel in figures.items():
            lines += [f"![{caption}]({rel})", "", f"*{caption}*", ""]
    return "\n".join(lines).rstrip() + "\n"


def _style_axes(ax, grid_axis: str) -> None:
    ax.set_facecolor(SURFACE)
    for side in ("top", "right", "left", "bottom"):
        ax.spines[side].set_visible(False)
    baseline = "left" if grid_axis == "x" else "bottom"
    ax.spines[baseline].set_visible(True)
    ax.spines[baseline].set_color(BASELINE)
    ax.spines[baseline].set_linewidth(0.8)
    ax.grid(axis=grid_axis, color=GRID, linewidth=0.5, linestyle="-")
    ax.set_axisbelow(True)
    ax.tick_params(colors=INK_MUTED, labelcolor=INK_SECONDARY, length=0)


def plot_class_distribution(summary: dict[str, dict], path: Path) -> Path:
    """Horizontal grouped bars: windows per activity for train, val and test (PNG, 300 dpi)."""
    counts = {s: class_counts(summary[s]["labels"]) for s in SPLITS}
    fig = Figure(figsize=(3.5, 2.7), facecolor=SURFACE, layout="constrained")
    ax = fig.subplots()
    _style_axes(ax, grid_axis="x")

    rows = np.arange(N_CLASSES)
    thickness = 0.24            # three bars per row, leaving air between activities
    for k, (split, color) in enumerate(zip(SPLITS, SERIES)):
        offset = (k - 1) * (thickness + 0.03)   # small surface gap between neighbouring bars
        ax.barh(rows + offset, counts[split], height=thickness, color=color,
                label=f"{split.capitalize()} ({int(counts[split].sum()):,})")

    ax.set_yticks(rows, [activity_label(n) for n in ACTIVITY_NAMES], fontsize=7)
    ax.invert_yaxis()           # first activity at the top
    ax.tick_params(axis="x", labelsize=6.5)
    ax.xaxis.set_major_formatter(lambda v, _pos: f"{int(v):,}")
    ax.set_xlabel("Windows", fontsize=7, color=INK_SECONDARY)
    # Legend in one row above the bars (the report adds the figure caption, so no title).
    fig.legend(fontsize=6.5, frameon=False, loc="outside upper center", ncol=3,
               labelcolor=INK_SECONDARY, handlelength=1.0, handleheight=0.8, columnspacing=1.2)
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=300, facecolor=SURFACE)
    return path


def pick_example_windows(labels: np.ndarray, subjects: np.ndarray,
                         candidate_subjects: list[int]) -> tuple[int, list[int]]:
    """One window per activity from a single subject, away from activity transitions.

    Uses the lowest-numbered candidate subject that performed all activities and takes the
    middle window of that subject's windows for each activity. Returns (subject, indices).
    """
    for subject in sorted(candidate_subjects):
        own = subjects == subject
        if all(np.any(own & (labels == c)) for c in range(N_CLASSES)):
            indices = []
            for c in range(N_CLASSES):
                where = np.flatnonzero(own & (labels == c))
                indices.append(int(where[len(where) // 2]))
            return subject, indices
    raise ValueError("no candidate subject has windows of every activity")


def plot_sample_windows(x: np.ndarray, labels: np.ndarray, subjects: np.ndarray,
                        candidate_subjects: list[int], path: Path) -> Path:
    """Body acceleration x/y/z of one window per activity, one panel each (PNG, 200 dpi).

    ``x`` is raw (unstandardised) ``(N, 128, 9)`` data in ``CHANNELS`` order, units of g.
    """
    subject, indices = pick_example_windows(labels, subjects, candidate_subjects)
    channels = [CHANNELS.index(f"body_acc_{axis}") for axis in "xyz"]
    t = np.arange(x.shape[1]) / SAMPLE_RATE_HZ

    fig = Figure(figsize=(7.0, 3.8), facecolor=SURFACE, layout="constrained")
    axes = fig.subplots(2, 3, sharex=True, sharey=True)
    for c, (ax, idx) in enumerate(zip(axes.flat, indices)):
        _style_axes(ax, grid_axis="y")
        for axis, ch, color in zip("xyz", channels, SERIES):
            ax.plot(t, x[idx, :, ch], color=color, linewidth=1.0, solid_joinstyle="round",
                    solid_capstyle="round", label=f"body_acc_{axis}")
        ax.set_title(activity_label(ACTIVITY_NAMES[c]), fontsize=8, color=INK, loc="left")
        ax.tick_params(labelsize=7)
    for ax in axes[:, 0]:
        ax.set_ylabel("Body acceleration (g)", fontsize=7, color=INK_SECONDARY)
    for ax in axes[-1, :]:
        ax.set_xlabel("Time (s)", fontsize=7, color=INK_SECONDARY)
    handles, names = axes.flat[0].get_legend_handles_labels()
    fig.legend(handles, names, loc="outside upper right", ncol=3, fontsize=7,
               frameon=False, labelcolor=INK_SECONDARY, handlelength=1.5)
    fig.suptitle(f"One {WINDOW_LEN / SAMPLE_RATE_HZ:.2f} s window per activity (training subject {subject})",
                 fontsize=9, color=INK, x=0.01, ha="left")
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=200, facecolor=SURFACE)
    return path


def _relative(path: Path, start: Path) -> str:
    """POSIX path of ``path`` relative to ``start`` (for markdown links), else as given."""
    try:
        return path.resolve().relative_to(start.resolve()).as_posix()
    except ValueError:
        return path.as_posix()


def write_dataset_report(out_md: Path, figures_dir: Path, uci_dir: Path = UCI_DIR,
                         split_file: Path = SPLIT_FILE) -> dict[str, Path]:
    """Write the statistics file and both figures; returns their paths keyed by name."""
    # Imported here: loading the raw signals is only needed for the sample-window figure.
    from har.data.raw import load_raw_split

    out_md, figures_dir = Path(out_md), Path(figures_dir)
    summary = summarise_splits(uci_dir, split_file)
    class_png = plot_class_distribution(summary, figures_dir / "class_distribution.png")

    x, y, subjects = load_raw_split("train", uci_dir)
    train_subjects = sorted(int(s) for s in np.unique(summary["train"]["subjects"]))
    sample_png = plot_sample_windows(x, y, subjects, train_subjects, figures_dir / "sample_windows.png")

    figures = {
        "Windows per activity in the train, validation and test splits": _relative(class_png, out_md.parent),
        "Body acceleration of one window per activity (raw signal, training subject)":
            _relative(sample_png, out_md.parent),
    }
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_md.write_text(stats_markdown(summary, figures), encoding="utf-8", newline="\n")
    return {"stats": out_md, "class_distribution": class_png, "sample_windows": sample_png}
